# Generated by Django 4.1.5 on 2023-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('Não iniciada', 'não iniciada'), ('Em Processo', 'em processo'), ('Finalizada', 'finalizada')], default='Não iniciada', max_length=13),
        ),
    ]
